### ISSUE TITLE
Sporadic "Command exited with code -1" on some Visual Studio 2017 builds

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#1490]
Discussion: http://help.appveyor.com/discussions/problems/6465-vs-2017-image-was-building-fine-then-fails-ever-since-2-days-ago

**Comment by jagerman** [comment]
Still failing.  I have no idea how to debug this.  I've tried enabling RDP access on failure, re-running the build on the exact same appveyor image where it just failed, out of the same build directory, and it succeeds every time.

I tried the build in a loop on a local VM (with Windows 10 + VS2017), and 100/100 builds passed.

**Comment by jagerman** [comment]
(For now, I'm just ignoring the failures and waiting for the next image update).

**Comment by FeodorFitsner** [comment]
Can you do I repro solution in a public repository? I understand it's not happening with any project, but with only specific ones.

**Comment by jagerman** [comment]
Sorry, I don't follow: "I repro solution"

**Comment by jagerman** [comment]
More details/investigation/tracking in pybind/pybind11#792.

**Comment by FeodorFitsner** [comment]
Sorry, I meant do you have a public repository/build reproducing the issue.

**Comment by jagerman** [comment]
Ah, yes, the [pybind11](https://github.com/pybind/pybind11) repository exhibits it.

**Comment by jagerman** [comment]
Here's an interesting failure that didn't even make it to the pybind code before failing (cmake's initial does-the-compiler-work test failed): https://ci.appveyor.com/project/wjakob/pybind11/build/1.0.1691/job/etguctmxjas78jn2

**Comment by ThirteenAG** [comment]
I have this too, for example: https://ci.appveyor.com/project/ThirteenAG/widescreenfixespack/build/218
Usually rebuilding the same commit works, but "Command exited with code -1" definitely appears every once in a while.

**Comment by Neproify** [comment]
Same thing on https://ci.appveyor.com/project/Neproify/iv-network

**Comment by FeodorFitsner** [comment]
We've deployed [Visual Studio 2017 update - version 15.1 (26403.07)](https://github.com/appveyor/ci/issues/1501) to `Visual Studio 2017` image. It looks like it fixed the issue with exit code -1.

Could you guys please check and let me know how that worked?

**Comment by jagerman** [comment]
When did the update version get deployed?  The last -1 failure I saw was around 3 hours ago (several builds since haven't had a failure).

**Comment by FeodorFitsner** [comment]
@jagerman about an hour ago. Actually, we were using your project for verifying the fix: https://ci.appveyor.com/project/FeodorFitsner/pybind11/history 😄

**Comment by jagerman** [comment]
Cool! :)  I'll keep an eye on it and report back if I encounter any more.

**Comment by jagerman** [comment]
I just encountered another one:

https://ci.appveyor.com/project/wjakob/pybind11/build/1.0.1751/job/8ua0rcj9a8ie2ubr

This is the first one I've seen, so it seems greatly reduced but perhaps not entirely solved.

**Comment by FeodorFitsner** [comment]
OK. Let's try removing `/logger:%MSBuildLogger%` and see if that might be affecting the build.
Second, is there any way to get more detailed logging in case of error? If it exists with code -1 I bet there should be something in the detailed log - some error or warning.

**Comment by jagerman** [comment]
Back when this was occurring often—it is very rare now: this was the first failure I've seen since the update 11 days ago—I tried some builds without `/logger` and still got failures ([this one](https://ci.appveyor.com/project/jagerman/pybind11/build/1.0.542/job/tvfgot775qxqbg7f), for example—the log is really long as I also had MSBuild verbosity set to diagnostic mode, but there doesn't appear to be anything useful in that diagnostic output).

I also haven't been able to find anything useful in logs; though I admit Windows is a bit foreign to me, so I'm not entirely sure where to look for this (or even which program's logs I should be looking for).  Something in the Event Viewer?  Is there anything helpful I could add to the build script to grab any sort of system errors?

I also don't know what exit code -1 means: is that a process being killed by the system for some reason?  Or some internal MSBuild error?  (If I try killing MSBuild through task manager, I get a 1 as exit code).  And when an individual compilation fails, MSBuild recognizes that and compiler output appears.

**Comment by jagerman** [comment]
And a couple more: https://ci.appveyor.com/project/wjakob/pybind11/build/1.0.1760/job/bym09yatp2f7xb6e
https://ci.appveyor.com/project/jagerman/pybind11/build/1.0.683/job/tkqgq0c8rnfqvxwd

Until today, there hadn't been any such failures since this issue was closed AFAIK.  Did something change in the VS 2017?

**Comment by FeodorFitsner** [comment]
Will take a look. This maybe some scheduling task or some built-in check for updates (Windows updates are disabled) interfering with the build process.

**Comment by Neproify** [comment]
Still happening on https://ci.appveyor.com/project/Neproify/iv-network

**Comment by FeodorFitsner** [comment]
Hopefully, that will be fixed with the next update as we disabled most of VS-related scheduled tasks.

**Comment by jagerman** [comment]
Seems to be working so far; all builds for the last couple days have been good.

**Comment by FeodorFitsner** [comment]
Cool, thanks for the update!
