### ISSUE TITLE
Order test results in the order they were executed

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#239]
Discussion: http://help.appveyor.com/discussions/suggestions/654-ordering-of-tests-on-build-page

**Comment by mattwarren** [comment]
Thinking about it a bit more, it also also might be nice to have some sort of hierarchy, i.e. something *like* this:

```
MiniBench.Tests.dll
  MiniBench.Tests.AnalyserTests
    AnalyseBenchmark_CanAnalyseSimpleBenchmark                              8 ms
    AnalyseBenchmark_CanAnalyseWhenBlackholeIsNeededPredefinedType        203 ms
    AnalyseBenchmark_CanAnalyseParamsWithStepsForField                     40 ms
    AnalyseBenchmark_CanAnalyseEmptyClass                           2 sec 161 ms

ConsoleApp-3_0.exe
  ConsoleApp_3_0
    SampleBenchmark_3_0.BasicTest                                         464 ms

Features.dll 
  Features
    ParamsWithStepsTestProperty.BasicTest                                  93 ms
    IterationParamsTest.BasicTest                                         462 ms
...

**Comment by Turbo87** [comment]
@FeodorFitsner is there any chance of this problem getting fixed in the near future?

**Comment by FeodorFitsner** [comment]
yes, of course - we'll fix that when start re-working tests experience. Though I can't give you ETA right now.

**Comment by adamralph** [comment]
I would like to see tests ordered alphabetically. Is that also something that's being worked on? Perhaps as a config option?

This is important when running [xBehave.net scenarios](http://xbehave.github.io/), e.g. https://ci.appveyor.com/project/adamralph/cola/build/tests

**Comment by tlindsay42** [comment]
This is either still an issue or has reoccurred.  Same issue occurs for Messages as well.

**Comment by adamralph** [comment]
I'd love to see something implemented here. The output from xbehave scenarios is still gibberish, with the random ordering: https://ci.appveyor.com/project/adamralph/bullseye/build/job/hc3b5w00maeadtuo/tests

(They need to be alphanumerically sorted to make sense.)

**Comment by adamralph** [comment]
I've spun off the low hanging fruit (alphanumeric sorting) into #2621.
