### ISSUE TITLE
Slack notifications fails on private channel

### ISSUE THREAD

**Issue by MartinDelille** [appveyor/ci#623]
I tried to set up Slash notification to my private channel using the following configuration (*xxxxxx* is my token encrypted [here](https://ci.appveyor.com/tools/encrypt):

    notifications:
      - provider: Slack
        channel: dev
        auth_token:
          secure: xxxxxx

My [Appveyor build](https://ci.appveyor.com/project/MartinDelille/travistest/build/1.0.307) show me the folloing error:

    Error sending Slack notification: Error sending Slack message: channel_not_found

When testing the Slash api with the following URL, it works: https://slack.com/api/chat.postMessage?token=xxxxxx&channel=dev&text=hello&pretty=1 (where *xxxxxx* is my token without encryption).

It also works if the channel is not private.

**Comment by FeodorFitsner** [comment]
Thanks for reporting about that. Will fix that shortly.

**Comment by FeodorFitsner** [comment]
The problem was AppVeyor always adding `#` to channel name thus making it work with public channels only.

**Comment by MartinDelille** [comment]
Ok let me know when it's available, I'll test it right away!

**Comment by FeodorFitsner** [comment]
Update with fix has been deployed.

**Comment by MartinDelille** [comment]
It works like a charm!

**Comment by Jeavon** [comment]
To check, this means we need to update all channel properties to include the # where we didn't need them previously?

**Comment by FeodorFitsner** [comment]
Yes, correct.

**Comment by PureKrome** [comment]
@FeodorFitsner We're still having problems with this.

I'm looking at some oldish AV-project and clicked EXPORT YAML.

this is the output...

```
notifications:
- provider: Slack
  auth_token:
    secure: <snipped>
  channel: dev-cd
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false
```

the channel is `dev-cd` in that output. not `#dev-cd`. 

What should we be doing for the channel name, please? I'm confused :cry: :blush:

**Comment by FeodorFitsner** [comment]
Is it a public or private channel?

**Comment by PureKrome** [comment]
![](https://31.media.tumblr.com/d1372d5af8aa6e1133e450b260e91d3e/tumblr_inline_n4evgm9cv11solpjm.gif)

out (company) slack is invite only? is that private, then?

once you're inside our slack, anyone can join then `#dev-cd` channel.

**Comment by FeodorFitsner** [comment]
OK, then in appveyor.yml it should be:

    channel: '#dev-cd'

**Comment by PureKrome** [comment]
we had that originally and we were getting that error message. so then i added the `#` and we're still getting the error message.

**Comment by FeodorFitsner** [comment]
What error do you get? Make sure channel name is in *quotes* if starts with #.

**Comment by PureKrome** [comment]
So is this correct?
- **channels** are public: `channel: dev`  <-- notice no `quotes`
- **direct messages** are private: `channel: '#my-private-channel'` <-- notice `quotes` and `#`

**Comment by PureKrome** [comment]
or is it like this....

![image](https://cloud.githubusercontent.com/assets/899878/12995901/4c9824c8-d17f-11e5-9ea9-397cd3e78c48.png)

the padlocks are private?

(and i'm guessing **direct messages** are not a channel .. which is why they are in a different column, so they are not part of this topic).

**Comment by FeodorFitsner** [comment]
Correct, channel with lock sign is private.

**Comment by PureKrome** [comment]
Awesome. so when do we add the `#` again? to private (padlocked) channels only? Any channel?

**Comment by FeodorFitsner** [comment]
# is added to non-private (non-padlocked) channels only.

**Comment by PureKrome** [comment]
k. soz.

**Comment by ncclementi** [comment]
@FeodorFitsner I had the github integration working in a public channel, convert the channel to private and the messages stop showing up. How do I fix this? Thanks
